### ISSUE TITLE
Missing AutoCloseable in SubmissionPublisher

### ISSUE THREAD

**Issue by PongPong** [stefan-zobel/java9-concurrent-backport#2]
hi @stefan-zobel ,

I found the SubmissionPublisher didn't implement the AutoCloseable interface, 
when I tried to surround "try (SubmissionPublisher<...> pub = new SubmissionPublished<>())"

Regards
Pong

**Comment by stefan-zobel** [comment]
Hi Pong,

good catch, I've missed that.
I actually thought this project to be dead (it hasn't been updated for almost 2 years) and of no interest to anyone. I can fix that and publish a new version on Maven Central if you have a need for it (please let me know).

Regards,
Stefan

**Comment by PongPong** [comment]
Hi @stefan-zobel ,

Since we are using WebLogic 12c which shipped with jdk 8, we need a backport for the Flow API, or do you have recommendation of alternatives?

Regards
Pong

**Comment by stefan-zobel** [comment]
Hi @PongPong,

no, I don't know of any other backport of the Flow API specifically.
No problem, just give me a few days. I think I'll get to it the next weekend.

Regards,
Stefan

**Comment by PongPong** [comment]
Thanks @stefan-zobel

**Comment by stefan-zobel** [comment]
Hi @PongPong,

I've just pushed release 2.0.0 to Maven Central

Regards,
Stefan

**Comment by PongPong** [comment]
Amazing! thanks anyway
